<?php 

/*  Invoice - Core Class Psuedo Code for NBCS Network Plugin
Last Updated 22 Oct 2018
-------------

Description: - Invoice issuing is controlled here. Extends Transaction Sub Class. This seems like it is only a "receipt" of invoice that is recorded in the database and sent to the patron as a notice. There should then also be a link to pay the invoice. Where? Are these invoices generated by Stripe or PayPal? 


*/

namespace core;

use core/sub/NNTransaction;

class NNInvoice extends NNTransaction{
	
	
	//Properties

	public 
		$__ = '', //
		$__ = ''; //
	
	
	//Methods
	
	
/*
	Name: __construct
	Description: 
*/	
			
	
	public function __construct( $data ){
		
		$this->init( $data );
	}	
			
	
/*
	Name: init
	Description: 
*/	
			
	
	public function init( $data ){
		
		$this->set_data( $data );
		
	}	
			
	
				
/*
	Name: 
	Description: 
*/	
			
	
	public function __(){
		
		
	}	
			
/*
	Name: 
	Description: 
*/	
			
	
	public function __(){
		
		
	}	
		
	
}

?>